export interface ProjectDocument {
  id: string
  name: string
  type: string
  category: string
  size: string
  project: string
  projectId: string
  phase: string
  uploadDate: string
  lastModified: string
  status: "Draft" | "Under Review" | "Approved" | "Superseded"
  version: string
  author: string
  reviewer: string
  approver: string
  description: string
  tags: string[]
  relatedDocuments: string[]
  confidentiality: "Public" | "Internal" | "Confidential" | "Restricted"
  language: string
  pages: number
  checksum: string
}

export const enhancedDocuments: ProjectDocument[] = [
  {
    id: "DOC001",
    name: "Thwake Dam Feasibility Study Report",
    type: "PDF",
    category: "Feasibility Studies",
    size: "15.2 MB",
    project: "Thwake Multipurpose Dam",
    projectId: "LDP001",
    phase: "Phase 2: Feasibility Study",
    uploadDate: "2021-11-30",
    lastModified: "2021-12-15",
    status: "Approved",
    version: "v3.1",
    author: "Dr. James Mwangi",
    reviewer: "Prof. Sarah Kimani",
    approver: "Chief Engineer",
    description:
      "Comprehensive feasibility study including technical, economic, environmental and social analysis for Thwake Multipurpose Dam project",
    tags: ["Feasibility", "Technical Analysis", "Economic Study", "CFRD", "Multipurpose"],
    relatedDocuments: ["DOC007", "DOC012", "DOC018"],
    confidentiality: "Internal",
    language: "English",
    pages: 485,
    checksum: "SHA256:a1b2c3d4e5f6...",
  },
  {
    id: "DOC002",
    name: "High Grand Falls Environmental Impact Assessment",
    type: "PDF",
    category: "Environmental Studies",
    size: "8.7 MB",
    project: "High Grand Falls Dam",
    projectId: "LDP002",
    phase: "Phase 2: Feasibility Study",
    uploadDate: "2024-02-10",
    lastModified: "2024-03-05",
    status: "Under Review",
    version: "v2.0",
    author: "Dr. Mary Wanjiku",
    reviewer: "Environmental Review Panel",
    approver: "NEMA",
    description:
      "Environmental Impact Assessment for High Grand Falls Dam including biodiversity, social impact and mitigation measures",
    tags: ["EIA", "Environmental", "Biodiversity", "Social Impact", "Mitigation"],
    relatedDocuments: ["DOC008", "DOC013", "DOC019"],
    confidentiality: "Public",
    language: "English",
    pages: 324,
    checksum: "SHA256:b2c3d4e5f6g7...",
  },
  {
    id: "DOC003",
    name: "Karimenu II Construction Drawings - Set A",
    type: "DWG",
    category: "Technical Drawings",
    size: "45.3 MB",
    project: "Karimenu II Dam",
    projectId: "LDP003",
    phase: "Phase 4: Final Design",
    uploadDate: "2023-01-20",
    lastModified: "2023-02-14",
    status: "Approved",
    version: "v4.2",
    author: "Eng. Peter Ochieng",
    reviewer: "Design Review Panel",
    approver: "Chief Design Engineer",
    description:
      "Complete set of construction drawings for Karimenu II Dam including general arrangement, structural details and reinforcement drawings",
    tags: ["Construction Drawings", "Structural", "Concrete Gravity", "Reinforcement"],
    relatedDocuments: ["DOC009", "DOC014", "DOC020"],
    confidentiality: "Confidential",
    language: "English",
    pages: 156,
    checksum: "SHA256:c3d4e5f6g7h8...",
  },
  {
    id: "DOC004",
    name: "Koru-Soin Reconnaissance Report",
    type: "PDF",
    category: "Reconnaissance Studies",
    size: "12.1 MB",
    project: "Koru-Soin Multipurpose Dam",
    projectId: "LDP004",
    phase: "Phase 1: Reconnaissance",
    uploadDate: "2024-05-12",
    lastModified: "2024-05-20",
    status: "Approved",
    version: "v1.3",
    author: "Dr. Mary Wanjiku",
    reviewer: "Technical Review Committee",
    approver: "Project Director",
    description:
      "Initial reconnaissance study for Koru-Soin Dam including site assessment, preliminary investigations and project justification",
    tags: ["Reconnaissance", "Site Assessment", "Preliminary", "Multipurpose"],
    relatedDocuments: ["DOC010", "DOC021"],
    confidentiality: "Internal",
    language: "English",
    pages: 198,
    checksum: "SHA256:d4e5f6g7h8i9...",
  },
  {
    id: "DOC005",
    name: "Arror Dam Geotechnical Investigation Report",
    type: "PDF",
    category: "Geotechnical Studies",
    size: "18.5 MB",
    project: "Arror Dam",
    projectId: "LDP005",
    phase: "Phase 2: Feasibility Study",
    uploadDate: "2023-11-12",
    lastModified: "2023-12-01",
    status: "Approved",
    version: "v2.1",
    author: "Eng. Peter Ochieng",
    reviewer: "Geotechnical Review Panel",
    approver: "Chief Geotechnical Engineer",
    description:
      "Comprehensive geotechnical investigation including borehole data, laboratory tests, foundation design parameters and construction recommendations",
    tags: ["Geotechnical", "Foundation", "Borehole Data", "Laboratory Tests", "CFRD"],
    relatedDocuments: ["DOC011", "DOC015", "DOC022"],
    confidentiality: "Internal",
    language: "English",
    pages: 267,
    checksum: "SHA256:e5f6g7h8i9j0...",
  },
  {
    id: "DOC006",
    name: "Dam Safety Guidelines - NWHSA Standards",
    type: "PDF",
    category: "Standards & Guidelines",
    size: "5.8 MB",
    project: "All Projects",
    projectId: "GENERAL",
    phase: "All Phases",
    uploadDate: "2024-01-15",
    lastModified: "2024-01-15",
    status: "Approved",
    version: "v3.0",
    author: "Dr. Robert Kiprotich",
    reviewer: "Dam Safety Committee",
    approver: "Chief Executive",
    description:
      "Comprehensive dam safety guidelines and standards for all NWHSA dam projects including design criteria, monitoring requirements and emergency procedures",
    tags: ["Dam Safety", "Standards", "Guidelines", "Monitoring", "Emergency"],
    relatedDocuments: ["DOC023", "DOC024"],
    confidentiality: "Internal",
    language: "English",
    pages: 89,
    checksum: "SHA256:f6g7h8i9j0k1...",
  },
  {
    id: "DOC007",
    name: "Thwake Dam Hydrological Study",
    type: "PDF",
    category: "Hydrological Studies",
    size: "22.3 MB",
    project: "Thwake Multipurpose Dam",
    projectId: "LDP001",
    phase: "Phase 2: Feasibility Study",
    uploadDate: "2020-06-30",
    lastModified: "2020-07-15",
    status: "Approved",
    version: "v2.3",
    author: "Prof. Sarah Kimani",
    reviewer: "Hydrological Review Panel",
    approver: "Chief Hydrologist",
    description:
      "Detailed hydrological analysis including rainfall-runoff modeling, flood frequency analysis, reservoir operation studies and climate change assessment",
    tags: ["Hydrology", "Flood Analysis", "Reservoir Operations", "Climate Change", "Modeling"],
    relatedDocuments: ["DOC001", "DOC012", "DOC025"],
    confidentiality: "Internal",
    language: "English",
    pages: 356,
    checksum: "SHA256:g7h8i9j0k1l2...",
  },
  {
    id: "DOC008",
    name: "High Grand Falls Biodiversity Assessment",
    type: "PDF",
    category: "Environmental Studies",
    size: "14.7 MB",
    project: "High Grand Falls Dam",
    projectId: "LDP002",
    phase: "Phase 2: Feasibility Study",
    uploadDate: "2024-03-20",
    lastModified: "2024-04-02",
    status: "Under Review",
    version: "v1.2",
    author: "Dr. Mary Wanjiku",
    reviewer: "Biodiversity Experts Panel",
    approver: "Environmental Director",
    description:
      "Comprehensive biodiversity assessment including flora and fauna surveys, habitat mapping, species impact analysis and conservation measures",
    tags: ["Biodiversity", "Flora", "Fauna", "Habitat", "Conservation"],
    relatedDocuments: ["DOC002", "DOC013", "DOC026"],
    confidentiality: "Public",
    language: "English",
    pages: 278,
    checksum: "SHA256:h8i9j0k1l2m3...",
  },
  {
    id: "DOC009",
    name: "Karimenu II Technical Specifications",
    type: "PDF",
    category: "Technical Specifications",
    size: "9.4 MB",
    project: "Karimenu II Dam",
    projectId: "LDP003",
    phase: "Phase 4: Final Design",
    uploadDate: "2023-03-15",
    lastModified: "2023-03-28",
    status: "Approved",
    version: "v3.0",
    author: "Dr. James Mwangi",
    reviewer: "Specifications Review Panel",
    approver: "Chief Engineer",
    description:
      "Detailed technical specifications for Karimenu II Dam construction including concrete specifications, reinforcement requirements, quality control procedures and testing protocols",
    tags: ["Technical Specifications", "Concrete", "Quality Control", "Testing", "Construction"],
    relatedDocuments: ["DOC003", "DOC014", "DOC027"],
    confidentiality: "Confidential",
    language: "English",
    pages: 145,
    checksum: "SHA256:i9j0k1l2m3n4...",
  },
  {
    id: "DOC010",
    name: "Koru-Soin Topographical Survey Report",
    type: "PDF",
    category: "Survey Reports",
    size: "31.2 MB",
    project: "Koru-Soin Multipurpose Dam",
    projectId: "LDP004",
    phase: "Phase 1: Reconnaissance",
    uploadDate: "2024-04-25",
    lastModified: "2024-05-05",
    status: "Approved",
    version: "v1.1",
    author: "Eng. David Mutua",
    reviewer: "Survey Review Committee",
    approver: "Chief Surveyor",
    description:
      "Comprehensive topographical survey including digital terrain model, contour mapping, cross-sections and volume calculations for reservoir area",
    tags: ["Topographical Survey", "Digital Terrain Model", "Contours", "Volume Calculations"],
    relatedDocuments: ["DOC004", "DOC021", "DOC028"],
    confidentiality: "Internal",
    language: "English",
    pages: 89,
    checksum: "SHA256:j0k1l2m3n4o5...",
  },
]
