export interface ProjectPhase {
  id: number
  name: string
  description: string
  duration: string
  status: "completed" | "current" | "pending" | "on-hold"
  progress: number
  startDate: string
  endDate: string
  budget: string
  steps: ProjectStep[]
  deliverables: string[]
  experts: string[]
  dependencies: number[]
  risks: string[]
  milestones: Milestone[]
}

export interface ProjectStep {
  id: number
  name: string
  description: string
  status: "completed" | "current" | "pending"
  progress: number
  duration: string
  assignedExpert: string
  deliverables: string[]
  startDate: string
  endDate: string
}

export interface Milestone {
  id: number
  name: string
  date: string
  status: "completed" | "pending" | "overdue"
  description: string
}

export interface DamProject {
  id: string
  name: string
  location: string
  river: string
  county: string
  subCounty: string
  coordinates: { lat: number; lng: number }
  status: string
  overallProgress: number
  currentPhase: string
  contractor: string
  consultant: string
  projectManager: string
  startDate: string
  expectedCompletion: string
  totalBudget: string
  spentBudget: string
  damType: string
  purpose: string[]
  technicalSpecs: {
    height: string
    length: string
    capacity: string
    catchmentArea: string
    designLife: string
    spillwayType: string
    foundationType: string
  }
  phases: ProjectPhase[]
  documents: string[]
  contracts: string[]
  environmentalStatus: string
  safetyRecord: string
  communityImpact: {
    beneficiaries: number
    relocatedFamilies: number
    jobsCreated: number
    economicImpact: string
  }
}

// Realistic project phases for dam construction
export const damProjectPhases: ProjectPhase[] = [
  {
    id: 1,
    name: "Phase 1: Reconnaissance & Preliminary Studies",
    description: "Initial site investigation, feasibility assessment, and preliminary design studies",
    duration: "8-12 months",
    status: "completed",
    progress: 100,
    startDate: "2019-01-15",
    endDate: "2019-11-30",
    budget: "KES 450M",
    dependencies: [],
    risks: ["Weather delays", "Access road challenges", "Community resistance"],
    deliverables: [
      "Reconnaissance Report",
      "Topographical Survey",
      "Preliminary Geological Assessment",
      "Hydrological Data Collection",
      "Environmental Screening",
      "Socio-economic Baseline Study",
    ],
    experts: ["Project Engineer", "Surveyor", "Hydrologist", "Environmental Expert"],
    milestones: [
      {
        id: 1,
        name: "Site Access Established",
        date: "2019-02-28",
        status: "completed",
        description: "Access roads and temporary facilities completed",
      },
      {
        id: 2,
        name: "Topographical Survey Complete",
        date: "2019-05-15",
        status: "completed",
        description: "Detailed topographical mapping finished",
      },
      {
        id: 3,
        name: "Preliminary Studies Report",
        date: "2019-11-30",
        status: "completed",
        description: "Comprehensive reconnaissance report submitted",
      },
    ],
    steps: [
      {
        id: 1,
        name: "Site Reconnaissance",
        description: "Initial site visit and assessment of dam location",
        status: "completed",
        progress: 100,
        duration: "2 weeks",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Site Visit Report", "Photo Documentation"],
        startDate: "2019-01-15",
        endDate: "2019-01-29",
      },
      {
        id: 2,
        name: "Topographical Survey",
        description: "Detailed mapping of dam site and reservoir area",
        status: "completed",
        progress: 100,
        duration: "3 months",
        assignedExpert: "Eng. David Mutua",
        deliverables: ["Topographical Maps", "Digital Terrain Model"],
        startDate: "2019-02-01",
        endDate: "2019-05-15",
      },
      {
        id: 3,
        name: "Preliminary Geological Investigation",
        description: "Initial assessment of geological conditions",
        status: "completed",
        progress: 100,
        duration: "2 months",
        assignedExpert: "Eng. Peter Ochieng",
        deliverables: ["Geological Report", "Borehole Logs"],
        startDate: "2019-03-01",
        endDate: "2019-05-30",
      },
      {
        id: 4,
        name: "Hydrological Assessment",
        description: "Water resource assessment and flow analysis",
        status: "completed",
        progress: 100,
        duration: "4 months",
        assignedExpert: "Prof. Sarah Kimani",
        deliverables: ["Hydrological Report", "Flow Data Analysis"],
        startDate: "2019-02-15",
        endDate: "2019-06-30",
      },
      {
        id: 5,
        name: "Environmental Screening",
        description: "Initial environmental impact assessment",
        status: "completed",
        progress: 100,
        duration: "3 months",
        assignedExpert: "Dr. Mary Wanjiku",
        deliverables: ["Environmental Screening Report"],
        startDate: "2019-04-01",
        endDate: "2019-07-15",
      },
      {
        id: 6,
        name: "Socio-economic Baseline",
        description: "Assessment of social and economic conditions",
        status: "completed",
        progress: 100,
        duration: "2 months",
        assignedExpert: "Dr. Mary Wanjiku",
        deliverables: ["Baseline Study Report"],
        startDate: "2019-08-01",
        endDate: "2019-10-15",
      },
    ],
  },
  {
    id: 2,
    name: "Phase 2: Feasibility Study & Detailed Investigations",
    description:
      "Comprehensive feasibility analysis, detailed site investigations, and environmental impact assessment",
    duration: "18-24 months",
    status: "completed",
    progress: 100,
    startDate: "2019-12-01",
    endDate: "2021-11-30",
    budget: "KES 1.2B",
    dependencies: [1],
    risks: ["Geological uncertainties", "Environmental approval delays", "Funding constraints"],
    deliverables: [
      "Feasibility Study Report",
      "Environmental Impact Assessment",
      "Detailed Geological Investigation",
      "Geotechnical Report",
      "Economic Analysis",
      "Risk Assessment Report",
    ],
    experts: ["Project Engineer", "Geotechnical Engineer", "Environmental Expert", "Economist"],
    milestones: [
      {
        id: 4,
        name: "Detailed Investigations Complete",
        date: "2020-08-31",
        status: "completed",
        description: "All site investigations finished",
      },
      {
        id: 5,
        name: "EIA Approval",
        date: "2021-06-15",
        status: "completed",
        description: "Environmental approval obtained",
      },
      {
        id: 6,
        name: "Feasibility Report Approved",
        date: "2021-11-30",
        status: "completed",
        description: "Final feasibility study approved",
      },
    ],
    steps: [
      {
        id: 7,
        name: "Detailed Geological Investigation",
        description: "Comprehensive geological and geotechnical studies",
        status: "completed",
        progress: 100,
        duration: "6 months",
        assignedExpert: "Eng. Peter Ochieng",
        deliverables: ["Geological Report", "Geotechnical Analysis", "Foundation Design Parameters"],
        startDate: "2019-12-01",
        endDate: "2020-06-30",
      },
      {
        id: 8,
        name: "Environmental Impact Assessment",
        description: "Comprehensive environmental impact study",
        status: "completed",
        progress: 100,
        duration: "12 months",
        assignedExpert: "Dr. Mary Wanjiku",
        deliverables: ["EIA Report", "Environmental Management Plan", "Mitigation Measures"],
        startDate: "2020-01-15",
        endDate: "2021-01-31",
      },
      {
        id: 9,
        name: "Hydrological Modeling",
        description: "Advanced water resource modeling and analysis",
        status: "completed",
        progress: 100,
        duration: "8 months",
        assignedExpert: "Prof. Sarah Kimani",
        deliverables: ["Hydrological Model", "Flood Analysis", "Water Balance Study"],
        startDate: "2020-02-01",
        endDate: "2020-10-15",
      },
      {
        id: 10,
        name: "Economic & Financial Analysis",
        description: "Cost-benefit analysis and financial modeling",
        status: "completed",
        progress: 100,
        duration: "4 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Economic Analysis Report", "Financial Model", "Cost Estimates"],
        startDate: "2020-06-01",
        endDate: "2020-10-31",
      },
      {
        id: 11,
        name: "Risk Assessment",
        description: "Comprehensive project risk analysis",
        status: "completed",
        progress: 100,
        duration: "3 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Risk Register", "Risk Mitigation Plan"],
        startDate: "2021-03-01",
        endDate: "2021-06-15",
      },
      {
        id: 12,
        name: "Feasibility Report Compilation",
        description: "Integration of all studies into final feasibility report",
        status: "completed",
        progress: 100,
        duration: "3 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Final Feasibility Study Report"],
        startDate: "2021-08-01",
        endDate: "2021-11-30",
      },
    ],
  },
  {
    id: 3,
    name: "Phase 3: Preliminary Design",
    description: "Initial engineering design, layout optimization, and preliminary specifications",
    duration: "12-15 months",
    status: "completed",
    progress: 100,
    startDate: "2022-01-01",
    endDate: "2023-03-31",
    budget: "KES 800M",
    dependencies: [2],
    risks: ["Design optimization challenges", "Regulatory approval delays", "Technical complexities"],
    deliverables: [
      "Preliminary Design Report",
      "General Arrangement Drawings",
      "Preliminary Specifications",
      "Quantity Estimates",
      "Construction Schedule",
    ],
    experts: ["Structural Engineer", "Hydraulic Engineer", "Mechanical Engineer"],
    milestones: [
      {
        id: 7,
        name: "Design Concept Approved",
        date: "2022-05-31",
        status: "completed",
        description: "Basic design concept finalized",
      },
      {
        id: 8,
        name: "Preliminary Drawings Complete",
        date: "2022-12-15",
        status: "completed",
        description: "All preliminary drawings finished",
      },
      {
        id: 9,
        name: "Design Review Completed",
        date: "2023-03-31",
        status: "completed",
        description: "Independent design review finished",
      },
    ],
    steps: [
      {
        id: 13,
        name: "Dam Layout Design",
        description: "Optimization of dam alignment and layout",
        status: "completed",
        progress: 100,
        duration: "3 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Layout Drawings", "Alignment Studies"],
        startDate: "2022-01-01",
        endDate: "2022-04-15",
      },
      {
        id: 14,
        name: "Structural Design",
        description: "Preliminary structural design of dam components",
        status: "completed",
        progress: 100,
        duration: "6 months",
        assignedExpert: "Eng. Peter Ochieng",
        deliverables: ["Structural Drawings", "Load Calculations"],
        startDate: "2022-02-01",
        endDate: "2022-08-31",
      },
      {
        id: 15,
        name: "Hydraulic Design",
        description: "Design of spillway and outlet works",
        status: "completed",
        progress: 100,
        duration: "4 months",
        assignedExpert: "Prof. Sarah Kimani",
        deliverables: ["Hydraulic Calculations", "Spillway Design"],
        startDate: "2022-04-01",
        endDate: "2022-08-15",
      },
      {
        id: 16,
        name: "Quantity Estimation",
        description: "Preliminary quantity takeoffs and cost estimates",
        status: "completed",
        progress: 100,
        duration: "2 months",
        assignedExpert: "Eng. Grace Akinyi",
        deliverables: ["Bill of Quantities", "Cost Estimates"],
        startDate: "2022-10-01",
        endDate: "2022-12-15",
      },
      {
        id: 17,
        name: "Design Review",
        description: "Independent review of preliminary design",
        status: "completed",
        progress: 100,
        duration: "2 months",
        assignedExpert: "External Consultant",
        deliverables: ["Design Review Report", "Recommendations"],
        startDate: "2023-01-15",
        endDate: "2023-03-31",
      },
    ],
  },
  {
    id: 4,
    name: "Phase 4: Final Design & Documentation",
    description: "Detailed engineering design, construction drawings, and tender documentation",
    duration: "15-18 months",
    status: "current",
    progress: 75,
    startDate: "2023-04-01",
    endDate: "2024-09-30",
    budget: "KES 1.5B",
    dependencies: [3],
    risks: ["Design complexity", "Approval delays", "Specification changes"],
    deliverables: [
      "Final Design Report",
      "Construction Drawings",
      "Technical Specifications",
      "Tender Documents",
      "Construction Manual",
    ],
    experts: ["All Technical Experts", "Contract Specialist"],
    milestones: [
      {
        id: 10,
        name: "60% Design Review",
        date: "2023-10-31",
        status: "completed",
        description: "60% design milestone achieved",
      },
      {
        id: 11,
        name: "90% Design Review",
        date: "2024-03-31",
        status: "completed",
        description: "90% design milestone achieved",
      },
      {
        id: 12,
        name: "Final Design Approval",
        date: "2024-09-30",
        status: "pending",
        description: "Final design approval pending",
      },
    ],
    steps: [
      {
        id: 18,
        name: "Detailed Structural Design",
        description: "Final structural design and calculations",
        status: "completed",
        progress: 100,
        duration: "8 months",
        assignedExpert: "Eng. Peter Ochieng",
        deliverables: ["Structural Drawings", "Reinforcement Details", "Specifications"],
        startDate: "2023-04-01",
        endDate: "2023-12-15",
      },
      {
        id: 19,
        name: "Mechanical & Electrical Design",
        description: "Design of gates, valves, and electrical systems",
        status: "completed",
        progress: 100,
        duration: "6 months",
        assignedExpert: "Eng. Grace Akinyi",
        deliverables: ["M&E Drawings", "Equipment Specifications"],
        startDate: "2023-06-01",
        endDate: "2023-12-31",
      },
      {
        id: 20,
        name: "Construction Drawings",
        description: "Detailed construction and working drawings",
        status: "current",
        progress: 85,
        duration: "10 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Construction Drawings", "Detail Drawings"],
        startDate: "2023-08-01",
        endDate: "2024-06-30",
      },
      {
        id: 21,
        name: "Technical Specifications",
        description: "Detailed technical specifications for construction",
        status: "current",
        progress: 70,
        duration: "6 months",
        assignedExpert: "Dr. James Mwangi",
        deliverables: ["Technical Specifications", "Quality Standards"],
        startDate: "2024-01-01",
        endDate: "2024-07-31",
      },
      {
        id: 22,
        name: "Tender Documentation",
        description: "Preparation of tender and contract documents",
        status: "pending",
        progress: 0,
        duration: "3 months",
        assignedExpert: "Contract Specialist",
        deliverables: ["Tender Documents", "Contract Conditions"],
        startDate: "2024-06-01",
        endDate: "2024-09-30",
      },
    ],
  },
  {
    id: 5,
    name: "Phase 5: Procurement & Mobilization",
    description: "Contractor selection, contract award, and site mobilization",
    duration: "8-12 months",
    status: "pending",
    progress: 0,
    startDate: "2024-10-01",
    endDate: "2025-09-30",
    budget: "KES 300M",
    dependencies: [4],
    risks: ["Tender disputes", "Mobilization delays", "Contractor capacity"],
    deliverables: [
      "Tender Evaluation Report",
      "Contract Agreement",
      "Mobilization Plan",
      "Quality Assurance Plan",
      "Safety Plan",
    ],
    experts: ["Procurement Specialist", "Contract Manager", "Project Manager"],
    milestones: [
      {
        id: 13,
        name: "Tender Advertisement",
        date: "2024-10-15",
        status: "pending",
        description: "Tender documents advertised",
      },
      {
        id: 14,
        name: "Contract Award",
        date: "2025-03-31",
        status: "pending",
        description: "Construction contract awarded",
      },
      {
        id: 15,
        name: "Site Mobilization",
        date: "2025-09-30",
        status: "pending",
        description: "Contractor mobilized on site",
      },
    ],
    steps: [
      {
        id: 23,
        name: "Tender Process",
        description: "Advertising, evaluation, and contractor selection",
        status: "pending",
        progress: 0,
        duration: "6 months",
        assignedExpert: "Procurement Specialist",
        deliverables: ["Tender Advertisement", "Evaluation Report", "Award Recommendation"],
        startDate: "2024-10-01",
        endDate: "2025-04-15",
      },
      {
        id: 24,
        name: "Contract Finalization",
        description: "Contract negotiation and signing",
        status: "pending",
        progress: 0,
        duration: "2 months",
        assignedExpert: "Contract Manager",
        deliverables: ["Signed Contract", "Performance Bonds"],
        startDate: "2025-04-01",
        endDate: "2025-06-15",
      },
      {
        id: 25,
        name: "Site Mobilization",
        description: "Contractor mobilization and site setup",
        status: "pending",
        progress: 0,
        duration: "3 months",
        assignedExpert: "Eng. Grace Akinyi",
        deliverables: ["Mobilization Certificate", "Site Facilities"],
        startDate: "2025-06-01",
        endDate: "2025-09-30",
      },
    ],
  },
  {
    id: 6,
    name: "Phase 6: Construction",
    description: "Physical construction of dam and associated works",
    duration: "48-60 months",
    status: "pending",
    progress: 0,
    startDate: "2025-10-01",
    endDate: "2030-09-30",
    budget: "KES 58.5B",
    dependencies: [5],
    risks: ["Weather delays", "Material supply", "Quality issues", "Safety incidents"],
    deliverables: [
      "Monthly Progress Reports",
      "Quality Control Reports",
      "Safety Reports",
      "Variation Orders",
      "Completion Certificates",
    ],
    experts: ["Construction Manager", "Site Engineer", "Quality Controller", "Safety Officer"],
    milestones: [
      {
        id: 16,
        name: "Foundation Complete",
        date: "2026-12-31",
        status: "pending",
        description: "Dam foundation completed",
      },
      {
        id: 17,
        name: "50% Construction",
        date: "2028-03-31",
        status: "pending",
        description: "Half construction completed",
      },
      {
        id: 18,
        name: "Dam Completion",
        date: "2030-06-30",
        status: "pending",
        description: "Dam construction finished",
      },
      {
        id: 19,
        name: "First Impounding",
        date: "2030-09-30",
        status: "pending",
        description: "First water impounding",
      },
    ],
    steps: [
      {
        id: 26,
        name: "Site Preparation",
        description: "Site clearing, access roads, and temporary facilities",
        status: "pending",
        progress: 0,
        duration: "6 months",
        assignedExpert: "Eng. Grace Akinyi",
        deliverables: ["Site Clearance Certificate", "Access Roads", "Temporary Facilities"],
        startDate: "2025-10-01",
        endDate: "2026-04-15",
      },
      {
        id: 27,
        name: "Foundation Excavation",
        description: "Excavation and preparation of dam foundation",
        status: "pending",
        progress: 0,
        duration: "12 months",
        assignedExpert: "Site Engineer",
        deliverables: ["Foundation Excavation", "Rock Treatment"],
        startDate: "2026-01-01",
        endDate: "2026-12-31",
      },
      {
        id: 28,
        name: "Dam Construction",
        description: "Main dam construction activities",
        status: "pending",
        progress: 0,
        duration: "36 months",
        assignedExpert: "Construction Manager",
        deliverables: ["Dam Structure", "Spillway", "Outlet Works"],
        startDate: "2026-06-01",
        endDate: "2029-06-30",
      },
      {
        id: 29,
        name: "Mechanical Works",
        description: "Installation of gates, valves, and equipment",
        status: "pending",
        progress: 0,
        duration: "12 months",
        assignedExpert: "Mechanical Engineer",
        deliverables: ["Gates Installation", "Control Systems"],
        startDate: "2029-01-01",
        endDate: "2030-01-15",
      },
      {
        id: 30,
        name: "Testing & Commissioning",
        description: "System testing and initial filling",
        status: "pending",
        progress: 0,
        duration: "8 months",
        assignedExpert: "Commissioning Engineer",
        deliverables: ["Test Reports", "Commissioning Certificate"],
        startDate: "2030-01-01",
        endDate: "2030-09-30",
      },
    ],
  },
  {
    id: 7,
    name: "Phase 7: Commissioning & Handover",
    description: "Final testing, commissioning, and project handover",
    duration: "6-12 months",
    status: "pending",
    progress: 0,
    startDate: "2030-10-01",
    endDate: "2031-09-30",
    budget: "KES 200M",
    dependencies: [6],
    risks: ["Performance issues", "Handover delays", "Training gaps"],
    deliverables: [
      "Commissioning Report",
      "Operation & Maintenance Manual",
      "As-Built Drawings",
      "Training Records",
      "Handover Certificate",
    ],
    experts: ["Operations Team", "Training Specialist", "Documentation Specialist"],
    milestones: [
      {
        id: 20,
        name: "Performance Tests",
        date: "2031-03-31",
        status: "pending",
        description: "Performance testing completed",
      },
      {
        id: 21,
        name: "Staff Training",
        date: "2031-06-30",
        status: "pending",
        description: "Operations staff trained",
      },
      {
        id: 22,
        name: "Project Handover",
        date: "2031-09-30",
        status: "pending",
        description: "Project officially handed over",
      },
    ],
    steps: [
      {
        id: 31,
        name: "Performance Testing",
        description: "Comprehensive testing of all systems",
        status: "pending",
        progress: 0,
        duration: "4 months",
        assignedExpert: "Test Engineer",
        deliverables: ["Performance Test Reports", "Defect Lists"],
        startDate: "2030-10-01",
        endDate: "2031-02-15",
      },
      {
        id: 32,
        name: "Documentation Finalization",
        description: "Completion of all project documentation",
        status: "pending",
        progress: 0,
        duration: "6 months",
        assignedExpert: "Documentation Specialist",
        deliverables: ["O&M Manuals", "As-Built Drawings", "Warranty Documents"],
        startDate: "2031-01-01",
        endDate: "2031-07-15",
      },
      {
        id: 33,
        name: "Staff Training",
        description: "Training of operations and maintenance staff",
        status: "pending",
        progress: 0,
        duration: "3 months",
        assignedExpert: "Training Specialist",
        deliverables: ["Training Programs", "Competency Certificates"],
        startDate: "2031-04-01",
        endDate: "2031-07-15",
      },
      {
        id: 34,
        name: "Final Handover",
        description: "Official project handover to operations",
        status: "pending",
        progress: 0,
        duration: "1 month",
        assignedExpert: "Project Manager",
        deliverables: ["Handover Certificate", "Final Report"],
        startDate: "2031-08-01",
        endDate: "2031-09-30",
      },
    ],
  },
]

// Enhanced project data with realistic connections
export const enhancedProjects: DamProject[] = [
  {
    id: "LDP001",
    name: "Thwake Multipurpose Dam",
    location: "Makueni County",
    river: "Athi River",
    county: "Makueni",
    subCounty: "Kibwezi East",
    coordinates: { lat: -2.4569, lng: 37.9083 },
    status: "Construction Phase",
    overallProgress: 75,
    currentPhase: "Phase 4: Final Design & Documentation",
    contractor: "China Gezhouba Group Company Limited (CGGC)",
    consultant: "Nippon Koei Co. Ltd & Associated Consultants",
    projectManager: "Dr. James Mwangi",
    startDate: "2019-01-15",
    expectedCompletion: "2031-09-30",
    totalBudget: "KES 63.5B",
    spentBudget: "KES 47.6B",
    damType: "Concrete Faced Rock Fill Dam (CFRD)",
    purpose: ["Water Supply", "Irrigation", "Flood Control"],
    technicalSpecs: {
      height: "80 meters",
      length: "1,200 meters",
      capacity: "681 million m³",
      catchmentArea: "18,500 km²",
      designLife: "100 years",
      spillwayType: "Gated Spillway",
      foundationType: "Rock Foundation",
    },
    phases: damProjectPhases,
    documents: ["DOC001", "DOC003", "DOC007", "DOC012"],
    contracts: ["CNT001", "CNT005"],
    environmentalStatus: "EIA Approved - NEMA License No. NEMA/EIA/PROJ/1234",
    safetyRecord: "Zero Lost Time Incidents - 2.1M Safe Hours",
    communityImpact: {
      beneficiaries: 1200000,
      relocatedFamilies: 156,
      jobsCreated: 2500,
      economicImpact: "KES 15B annual economic benefit",
    },
  },
  {
    id: "LDP002",
    name: "High Grand Falls Dam",
    location: "Tana River County",
    river: "Tana River",
    county: "Tana River",
    subCounty: "Galole",
    coordinates: { lat: -1.2921, lng: 40.1169 },
    status: "Feasibility Study",
    overallProgress: 25,
    currentPhase: "Phase 2: Feasibility Study & Detailed Investigations",
    contractor: "TBD - Tender Process Pending",
    consultant: "Lahmeyer International & Local Partners",
    projectManager: "Eng. Sarah Kimani",
    startDate: "2024-01-10",
    expectedCompletion: "2035-12-31",
    totalBudget: "KES 120B",
    spentBudget: "KES 8.5B",
    damType: "Concrete Arch Dam",
    purpose: ["Hydropower Generation", "Water Supply", "Irrigation"],
    technicalSpecs: {
      height: "165 meters",
      length: "800 meters",
      capacity: "5.6 billion m³",
      catchmentArea: "95,000 km²",
      designLife: "100 years",
      spillwayType: "Overflow Spillway",
      foundationType: "Rock Foundation",
    },
    phases: damProjectPhases.map((phase) => ({
      ...phase,
      status: phase.id <= 2 ? "current" : ("pending" as any),
      progress: phase.id === 1 ? 100 : phase.id === 2 ? 45 : 0,
    })),
    documents: ["DOC002", "DOC008", "DOC013"],
    contracts: ["CNT002"],
    environmentalStatus: "EIA Study Ongoing",
    safetyRecord: "No incidents reported",
    communityImpact: {
      beneficiaries: 2500000,
      relocatedFamilies: 450,
      jobsCreated: 5000,
      economicImpact: "KES 35B annual economic benefit",
    },
  },
  {
    id: "LDP003",
    name: "Karimenu II Dam",
    location: "Kiambu County",
    river: "Chania River",
    county: "Kiambu",
    subCounty: "Gatundu North",
    coordinates: { lat: -0.9833, lng: 36.8167 },
    status: "Near Completion",
    overallProgress: 95,
    currentPhase: "Phase 6: Construction",
    contractor: "Sinohydro Corporation Limited",
    consultant: "Associated Consulting Engineers (ACE)",
    projectManager: "Eng. Peter Ochieng",
    startDate: "2020-06-01",
    expectedCompletion: "2024-12-31",
    totalBudget: "KES 8.5B",
    spentBudget: "KES 8.1B",
    damType: "Concrete Gravity Dam",
    purpose: ["Water Supply", "Flood Control"],
    technicalSpecs: {
      height: "45 meters",
      length: "350 meters",
      capacity: "9.8 million m³",
      catchmentArea: "120 km²",
      designLife: "75 years",
      spillwayType: "Ogee Spillway",
      foundationType: "Rock Foundation",
    },
    phases: damProjectPhases.map((phase) => ({
      ...phase,
      status: phase.id <= 6 ? "completed" : phase.id === 7 ? "current" : ("pending" as any),
      progress: phase.id <= 6 ? 100 : phase.id === 7 ? 30 : 0,
    })),
    documents: ["DOC003", "DOC009", "DOC014"],
    contracts: ["CNT003", "CNT006"],
    environmentalStatus: "EIA Compliant - All Conditions Met",
    safetyRecord: "1 Minor Incident - 1.8M Safe Hours",
    communityImpact: {
      beneficiaries: 500000,
      relocatedFamilies: 23,
      jobsCreated: 800,
      economicImpact: "KES 2.5B annual economic benefit",
    },
  },
  {
    id: "LDP004",
    name: "Koru-Soin Multipurpose Dam",
    location: "Kisumu County",
    river: "Nyando River",
    county: "Kisumu",
    subCounty: "Muhoroni",
    coordinates: { lat: -0.1667, lng: 35.2833 },
    status: "Planning Phase",
    overallProgress: 15,
    currentPhase: "Phase 1: Reconnaissance & Preliminary Studies",
    contractor: "TBD",
    consultant: "Knight Piésold & Partners",
    projectManager: "Dr. Mary Wanjiku",
    startDate: "2024-03-01",
    expectedCompletion: "2038-06-30",
    totalBudget: "KES 45B",
    spentBudget: "KES 2.1B",
    damType: "Earth Core Rock Fill Dam",
    purpose: ["Irrigation", "Water Supply", "Flood Control", "Fisheries"],
    technicalSpecs: {
      height: "72 meters",
      length: "2,100 meters",
      capacity: "350 million m³",
      catchmentArea: "3,500 km²",
      designLife: "100 years",
      spillwayType: "Side Channel Spillway",
      foundationType: "Alluvial Foundation",
    },
    phases: damProjectPhases.map((phase) => ({
      ...phase,
      status: phase.id === 1 ? "current" : ("pending" as any),
      progress: phase.id === 1 ? 60 : 0,
    })),
    documents: ["DOC004", "DOC010"],
    contracts: ["CNT004"],
    environmentalStatus: "Environmental Screening Complete",
    safetyRecord: "No incidents - Project in early phase",
    communityImpact: {
      beneficiaries: 800000,
      relocatedFamilies: 89,
      jobsCreated: 1500,
      economicImpact: "KES 8B annual economic benefit",
    },
  },
  {
    id: "LDP005",
    name: "Arror Dam",
    location: "Elgeyo Marakwet County",
    river: "Arror River",
    county: "Elgeyo Marakwet",
    subCounty: "Kerio Valley",
    coordinates: { lat: 1.0833, lng: 35.6167 },
    status: "Design Phase",
    overallProgress: 40,
    currentPhase: "Phase 3: Preliminary Design",
    contractor: "TBD",
    consultant: "Gibb Africa & Local Associates",
    projectManager: "Eng. David Mutua",
    startDate: "2023-08-15",
    expectedCompletion: "2034-03-31",
    totalBudget: "KES 28B",
    spentBudget: "KES 4.2B",
    damType: "Concrete Faced Rock Fill Dam (CFRD)",
    purpose: ["Water Supply", "Irrigation"],
    technicalSpecs: {
      height: "96 meters",
      length: "650 meters",
      capacity: "185 million m³",
      catchmentArea: "1,200 km²",
      designLife: "100 years",
      spillwayType: "Chute Spillway",
      foundationType: "Rock Foundation",
    },
    phases: damProjectPhases.map((phase) => ({
      ...phase,
      status: phase.id <= 2 ? "completed" : phase.id === 3 ? "current" : ("pending" as any),
      progress: phase.id <= 2 ? 100 : phase.id === 3 ? 65 : 0,
    })),
    documents: ["DOC005", "DOC011", "DOC015"],
    contracts: ["CNT007"],
    environmentalStatus: "EIA Approved with Conditions",
    safetyRecord: "No incidents reported",
    communityImpact: {
      beneficiaries: 350000,
      relocatedFamilies: 67,
      jobsCreated: 1200,
      economicImpact: "KES 4.5B annual economic benefit",
    },
  },
]
